# Generated by Django 3.2.8 on 2021-11-18 08:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('create_time', models.DateTimeField()),
                ('expire_time', models.DateTimeField()),
            ],
        ),
    ]
