# Generated by Django 3.2.8 on 2022-06-13 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLake',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('config', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SparkConnector',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('config', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('datalake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spark_connectors', to='main.datalake')),
            ],
            options={
                'unique_together': {('datalake', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DataLakeUserPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datalake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.datalake')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('datalake', 'user', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='DataLakeGroupPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datalake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.datalake')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.permission')),
            ],
            options={
                'unique_together': {('datalake', 'group', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='DataLakeAdmin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datalake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.datalake')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('datalake', 'user')},
            },
        ),
    ]
