# Generated by Django 3.2.8 on 2021-11-21 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLake',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('config', models.TextField(blank=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('datalake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.datalake')),
            ],
            options={
                'unique_together': {('datalake', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PermissionGrant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_id', models.BigIntegerField(null=True)),
                ('datalake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.datalake')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'datalake', 'permission', 'target_id')},
            },
        ),
    ]
